# Generated by Django 5.2.8 on 2025-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_remove_userprofile_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID from Wyse Timetables (WTT3) API",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="External reservation ID",
            ),
        ),
    ]